apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: external-dns
resources:
  - external-secret.yaml
patches:
  - path: helm-release.yaml
    target:
      kind: HelmRelease
      name: external-dns-public
