apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../apps/bundles/talos-flex
  - istio
  - metallb
  - external-secrets
  - external-dns
  - cert-manager
patches:
  - path: external-dns/helm-release-patch.yaml
    target:
      kind: HelmRelease
      name: external-dns-public
      namespace: external-dns
  - path: metallb/namespace-patch.yaml
    target:
      kind: Namespace
      name: metallb-system
