apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/istio
  - ../../base/external-secrets
  - ../../base/reflector
  - ../../base/cloudnative-pg
  - ../../base/longhorn
  - ../../base/kubelinks
  - ../../base/victoria-metrics-k8s-stack
  - ../../base/metrics-server
  - ../../base/metallb
patches:
  - path: hetzner-talos.yaml
